digraph G {
n2[label="all", color="red"];
n11[label="analysis/stat_tests/stat_tests.csv", color="red"];
n7[label="data/processed/*", color="red"];
n9[label="data/raw/*", color="red"];
n3[label="docs/", color="red"];
n5[label="eda/figures/*", color="red"];
n4[label="reports/_build/", color="red"];
n10[label="src/download_datasets.py", color="green"];
n6[label="src/eda_script.py", color="green"];
n8[label="src/process_raw.py", color="green"];
n12[label="src/stat_tests.py", color="green"];
n3 -> n2 ; 
n7 -> n11 ; 
n12 -> n11 ; 
n9 -> n7 ; 
n8 -> n7 ; 
n10 -> n9 ; 
n4 -> n3 ; 
n7 -> n5 ; 
n6 -> n5 ; 
n11 -> n4 ; 
n5 -> n4 ; 
}
